import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import { CartProvider } from "@/context/cart/provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"]
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const iranianSans = localFont({
  src: '../../public/fonts/IranianSans.ttf',
  display: 'swap', // This ensures text remains visible during font load
  variable: '--font-iranian-sans', // CSS variable name for flexibility
  weight: '400'
})

const BYekan = localFont({
  src: '../../public/fonts/BYekan.ttf',
  display: 'swap', // This ensures text remains visible during font load
  variable: '--font-BYekan', // CSS variable name for flexibility
  weight: '400'
})

export const metadata: Metadata = {
  title: "Nav Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={` ${BYekan.variable} ${iranianSans.variable}  antialiased`}
      >

        <CartProvider>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            {children}
            <Footer />
          </div>
        </CartProvider>

      </body>
    </html>
  );
}
